### ISSUE TITLE
MissingResourceException in LoggerFactory.getLogger() method

### ISSUE THREAD

**Issue by FMestric** [StroeerSE/StroeerBeaconSDK_Android#6]
After implementing the new proguard rules that were included in the comments of issue #5 we re-enabled the Proxity SDK in the application and made a new release v5.0.1 (51). This release resulted in new issues, which forced us to disable the SDK once again.

One of the issues is MissingResourceException in LoggerFactory.getLogger() method. As before, we will provide links to our Crashlytics reports for the issue: http://crashes.to/s/5f8c97cb2c0

**Comment by Favendo** [comment]
Hi Filip,
thanks for your report. We will take care of it and try to solve your issue.

Best,
Favendo

**Comment by Favendo** [comment]
Hi @FMestric,

we did a make a small mistake in our last comment in issue #5: because we did not use "insert code" markup the browser did interpret asterisks and did not show the code properly. Again, with the  following keep statements
```
-keep class de.stroeer.** { *; }
-keep class org.eclipse.paho.** { *; }
```
in your proguard-rules.pro file the error should no longer occur.
