### ISSUE TITLE
NullPointerException in AnayticsService.run() method

### ISSUE THREAD

**Issue by fmestric-super** [StroeerSE/StroeerBeaconSDK_Android#8]
No further information is known about the issue. Link to the Crashlytics report: http://crashes.to/s/c86c421545a

**Comment by Favendo** [comment]
Hi @FMestric,

we have tried to reproduce the crash and found out that disabled Google Play Services may be the issue. We got exactly the same crash once we disabled these services.
Are the Google Play Services disabled on your device? If this is the case, please try to update and/or to activate them and let us know whether it solved the issue.

Furthermore, we will implement a null pointer check in the next version to avoid this problem in the future.

**Comment by Favendo** [comment]
Updates on the Issue:
- We added a null pointer check to prevent the possible crashes in case of the Google Play Services that provides Advertisement ID are down or disfunctional.

-Furthermore, we changed how the system behaves when services are unavailable. In the new version, whenever an exception occurs due to the disfuncional service, the system doesn't add an advertisement id and behaves in the same way (Settings>>Google>>Ads>>Opt out of Ads Personalisation) is on.

The new structure will be available in the upcoming release.

**Comment by FMestric** [comment]
You mentioned a upcoming release, is there a update when this update might come out?

**Comment by Favendo** [comment]
Hi @FMestric,

we have released the new version 2.2.4. In this version, the SDK will not crash when Google Play Services are disabled. It will simply not send the device's advertisement ID, as it is not able to retrieve it in that case.

**Comment by fmestric-happening** [comment]
If so there should be no problems in the next app release that will implement version 2.2.4 of the library.
